Add symbolic link for 'htop'
ubuntu/yaru pull request #2565
Opened 2021-01-25 10:21 UTC by vitalkanev

Supplemental pull request for https://github.com/ubuntu/yaru/issues/2517

/cc @Feichtmeier because he suggested symlink https://github.com/ubuntu/yaru/issues/2517#issuecomment-750221951

2021-01-28 11:25 UTC, Feichtmeier requested changes
Looking good!
Eventually, symlink the symbolic, too? :thinking:

2021-01-28 14:33 UTC, vitalkanev commented
> 
> 
> Looking good!
> Eventually, symlink the symbolic, too? 🤔

Don't think so...

2021-02-04 23:24 UTC, Feichtmeier commented
Yeah, but if you want to symlink the app icon, you also need to symlink the symbolic icon.
Otherwise you'll end up with the new shiny app icon and the old symbolic

2021-02-05 12:33 UTC, Feichtmeier approved these changes

2021-02-05 12:34 UTC, merged