Add symbolic Snap mimetype icon
ubuntu/yaru pull request #2835
Opened 2021-05-14 12:22 UTC by elsiehupp

Fixes https://github.com/ubuntu/yaru/issues/2403.

I based the icon name on the name of [the corresponding fullcolor icon](https://github.com/ubuntu/yaru/blob/master/icons/src/fullcolor/mimetypes/application-vnd.snap.svg).

The primary change I made when scaling down the full-size icon was thickening the negative-space lines and aligning them to the pixel grid so that the icon will look sharper when rendered on screen. There are a number of side-by-side previews in the linked Issue.

Please let me know if there's anything else I need to do for the pull request. (I'm new here.) Thanks!

2021-05-14 13:00 UTC, Jupi007 requested changes
Hi @elsiehupp,
thanks a lot for your PR.

The SVG itself is great.

But there's a few more steps to do:
- That not very important, but we usually use a mid-grey `#808080` for our symbolic icons.
- Also you only added your icon into the `/src` folder. You must to use the render script which will export a minimized version into `/Suru`. Run it like this: `./render-symbolic-icons.sh -c mimetypes -f application-vnd.snap-symbolic.svg`

Thanks :)

2021-05-14 15:32 UTC, elsiehupp commented
Okay, cool! The version I initially posted just didn’t have color data to begin with, but it was easy enough for me to add it to the SVG.

Is it all good, now?

2021-05-14 15:39 UTC, elsiehupp commented
Actually, one thing: It looks like the norm is for mimetypes to be inside outlines, so this should probably be an application icon, not a mimetype icon.

2021-05-14 17:01 UTC, elsiehupp commented
I moved the existing icon into “apps” and added a separate mimetype icon based on the existing norm of roundrect outlines.

2021-05-14 17:35 UTC, Jupi007 approved these changes
Looks good for me, thanks for this @elsiehupp 👍

I have an off topic question: what do you use to edit your SVG?

2021-05-14 17:39 UTC, Muqtxdir commented
@elsiehupp had a look at this branch, the icons look really good and nicely aligned.

2021-05-14 18:15 UTC, elsiehupp commented
> Looks good for me, thanks for this @elsiehupp 👍
> 
> I have an off topic question: what do you use to edit your SVG?

I use [Affinity Designer](https://affinity.serif.com/designer/) on macOS. I used to use Illustrator, but Affinity had a 50% “work from home” sale at the beginning the pandemic, and Affinity has a pay-once business model, whereas Adobe has a monthly subscription business model.

I’ve been wading through lots of raw SVG lately, and Affinity seems to generate much cleaner output than Inkscape, Illustrator, or Vectornator. Inkscape uses a bunch of SVG extensions in order to use SVG as its primary format, but the result is that there’s a lot of extraneous stuff left over in the raw SVG. Affinity doesn’t support any of the more clever programmatic features of SVG (I think Inkscape might, but I’m not sure), but it’s still fairly good as a starting point.

As an aside, doing my illustration work on macOS is why I’m getting [pesky `.DS_Store` files](https://github.com/ubuntu/yaru/pull/2836) everywhere. It might be because I’m using [Netatalk](http://netatalk.sourceforge.net/) instead of Samba, idk.

> @elsiehupp had a look at this branch, the icons look really good and nicely aligned.

Thanks! 😊

2021-05-14 18:30 UTC, Jupi007 commented
@elsiehupp Thanks for your answer :)
In fact I ask this because as you seems to want to contribute, you must use Inkscape because we use some specifics Inkscape's metadata and any other software will brake the workflow.
But don't worry, it is just for fullcolor icons, symbolics ones are not affected.

2021-05-14 18:34 UTC, elsiehupp commented
> @elsiehupp Thanks for your answer :)
> In fact I ask this because as you seems to want to contribute, you must use Inkscape because we use some specifics Inkscape's metadata and any other software will brake the workflow.
> But don't worry, it is just for fullcolor icons, symbolics ones are not affected.

You mean like [this](https://github.com/linuxmint/mint-y-icons/pull/285)? (I haven’t actually checked to see if you’re using the same Python script, but I’d be shocked if you weren’t.)

2021-05-14 18:50 UTC, elsiehupp commented
[It was, in fact, the same Python script.](https://github.com/ubuntu/yaru/pull/2839)

2021-05-16 18:22 UTC, Jupi007 commented
@ubuntujaggers I think we can merge this, wdyt?

2021-05-16 18:26 UTC, merged

2021-05-16 19:04 UTC, elsiehupp commented
FYI one of the icons here [uses stroke width instead of fill](https://github.com/ubuntu/yaru/pull/2843#issuecomment-841855455), so idk if it will work properly.

2021-05-16 19:12 UTC, Jupi007 commented
Sorry, I didn't tell you earlier that using stroke is problematic.
Can you make a patch PR?