cinnamon: make it true in rules and refine assets
ubuntu/yaru pull request #3333
Opened 2022-01-27 07:57 UTC by Muqtxdir

- use true for `cinnamon` in `rules` for `yaru-theme-gtk.install`
- improve/refine assets under `cinnamon/`:
  - [x] use `16x16` for checkboxes and `26x26` for close.
  - [x] improve `checkbox-*`, `switch-*`, `calendar-*`, `close-*`

2022-01-27 09:14 UTC, Jupi007 reviewed
Hi @Muqtxdir 👋
Thanks for working on this.

I added some comments :)

2022-01-28 19:02 UTC, ItzSwirlz commented on debian/yaru-theme-gtk.install
> +usr/share/themes/Yaru-dark/cinnamon
If we did for xfce we should here

2022-01-28 19:03 UTC, ItzSwirlz commented
This would be great. This weekend I'll review the theme and nitpick issues

2022-01-28 19:19 UTC, Jupi007 commented on debian/yaru-theme-gtk.install
> +usr/share/themes/Yaru-dark/cinnamon
Well that very different in fact.
Yaru `xfce` component, are just some assets to have correct headerbars.

Here with cinnamon we have a brand new desktop theme.
IMO we should add a new package.

2022-01-28 21:20 UTC, ItzSwirlz commented
Am I the only one who sees the Bluetooth icon as blurry?![image](https://user-images.githubusercontent.com/24401303/151623000-bd2a8284-a51a-4406-a3fa-08fe97b29bb7.jpeg)

2022-02-03 19:23 UTC, Jupi007 requested changes

2022-02-03 19:23 UTC, Jupi007 commented on debian/yaru-theme-gtk.install
> +usr/share/themes/Yaru-dark/cinnamon
@Muqtxdir Everything looks good for me, except this ;)

2022-02-03 19:31 UTC, Muqtxdir commented
I didn't do this because it may conflict and confusion with packages from Ubuntu Cinnamon project, since there already exists a package named similarly as `yaru-theme-cinnamon` series. (_I think there was an issue like this_)

2022-02-03 19:36 UTC, Jupi007 commented
Ah, this is annoying...
I don't think we should wrap such a big thing like the cinnamon theme in `yaru-theme-gtk`.

It is possible to make a kind of migration with the Ubuntu Cinnamon's package?

2022-02-03 19:38 UTC, Muqtxdir commented
> It is possible to make a kind of migration with the Ubuntu Cinnamon's package?

It's possible to do this but Im not aware with full debian package replacement. @ItzSwirlz could you please help us out on this one? it looks like you maintain packages for ubuntu-cinnamon

2022-02-03 21:25 UTC, ItzSwirlz commented
> > It is possible to make a kind of migration with the Ubuntu Cinnamon's package?
> 
> 
> 
> It's possible to do this but Im not aware with full debian package replacement. @ItzSwirlz could you please help us out on this one? it looks like you maintain packages for ubuntu-cinnamon

I didn't know dh migratiosn exist. I moved Yaru-theme-cinnamon-* as part of the ubuntucinnamon-environment package. It's PPA though. I can rename my cinnamon variant to Yaru-cinnamon-theme-* and a migration or something will be setup

2022-02-11 10:40 UTC, Jupi007 commented
Thanks for your work on this @Muqtxdir :+1:

2022-02-11 10:40 UTC, merged