Add HWP Mimetype icon
ubuntu/yaru pull request #3458
Opened 2022-03-07 08:32 UTC by kuroehanako

2022-03-07 08:42 UTC, Muqtxdir commented
Hi @kuroehanako 

you do need to render the svgs

2022-03-07 08:59 UTC, Muqtxdir requested changes

2022-03-07 08:59 UTC, Muqtxdir commented on icons/src/fullcolor/default/mimetypes/applications-x-hwp.svg
> +           id="tspan3937">x-office-document</tspan></text>
The baseplate name should be changed from `x-office-document` to `applications-x-hwp` 

https://user-images.githubusercontent.com/54065734/156999697-dae78a7e-11a3-4b6b-a5e5-329f0395bb85.mp4

`

2022-03-07 10:14 UTC, kuroehanako commented
fixed problem.

2022-03-07 10:24 UTC, Muqtxdir commented
soory for the confusion, I meant changing the baseplate title from `x-office-document` to `application-x-hwp` (the one in layers) not just the doc-name.

_ then you also need to render the mimetype:_
```bash
# inside yaru/icons/src/fullcolor
./render-bitmaps.py application-x-hwp
```

2022-03-13 16:55 UTC, Muqtxdir approved these changes

2022-03-13 17:27 UTC, Jupi007 approved these changes
LGFM :+1:

2022-03-13 17:30 UTC, Muqtxdir commented
_@kuroehanako thanks for the nicely-done mimetype as a first-contribution towards yaru_
merging this !

2022-03-13 17:30 UTC, merged