feat: vlang icons
ubuntu/yaru pull request #3742
Opened 2022-09-27 11:24 UTC by enghitalo

creating icons to v programming language.
https://vlang.io/

2022-09-27 12:34 UTC, Muqtxdir commented
hi @enghitalo 

Thanks for taking time and making your first contribution towards yaru project. Could you please commit the source svg file from which you have rendered in this branch as well.

2022-09-27 13:40 UTC, enghitalo commented
> hi @enghitalo
> 
> Thanks for taking time and making your first contribution towards yaru project. Could you please commit the source svg file from which you have rendered in this branch as well.

Hi, @Muqtxdir.

Well, I don't know what is the pattern process to include new icons. I just edit one by one in gimp that don't export to svg format.

2022-09-27 14:15 UTC, enghitalo commented
@Muqtxdir Done.

2022-09-27 17:16 UTC, Jupi007 requested changes
Hi @enghitalo,
thanks a lot for your contribution!

I have a few note:

- the logo size on the the svg source looks inconsistent across the different size (48px is huge, 24px is to small imo) ;
- btw, did you used the script to render the pngs? It looks like they are not sync with the source file.
- on pngs, behind the logo, there is a very soft grey background which should be remove I think. But as it is not present on the svg, you'll just need to run the render script :)

2022-09-27 17:18 UTC, Jupi007 commented
Another note: where can I find the mimetype reference?

2022-09-27 18:57 UTC, enghitalo commented
I am happy to help.

> - the logo size on the the svg source looks inconsistent across the different size (48px is huge, 24px is to small imo);

Ok. I will try fix it.

> - btw, did you used the script to render the pngs? It looks like they are not sync with the source file.

I have not ideia of what is this script. Can you help with this?

> - on pngs, behind the logo, there is a very soft grey background which should be remove I think. But as it is not present on the svg, you'll just need to run the render script :)

Well the last added file (the svg one) is the best fit.

Sorry for all this errors, and thank for reviews. It is my first time here. I will try be better.

I have read the docs and I can't see to much about icon things. Like this script, for example.

2022-09-28 09:33 UTC, enghitalo commented
> The script is located at `/icons/src/fullcolor/render-bitmaps.py` :) Use it like this:
> 
> ```shell
> $ ./render-bitmaps.py <icon-name>
> ```
Thank you so much.

2022-09-28 10:09 UTC, Jupi007 requested changes
Mhh, sorry but I think you messed it up :D

There is now two svg files, and one is broken: _**application-x-v.svg**_
Btw, you need to use a folded corner on text mimetype icons (like you did in the first iteration).
Also, where did you found those mimetype names (**_application-v_** and _**application-x-v**_)?

Thanks :)

2022-09-28 10:44 UTC, enghitalo commented
> There is now two svg files, and one is broken: _**application-x-v.svg**_ Btw, you need to use a folded corner on text mimetype icons (like you did in the first iteration). Also, where did you found those mimetype names (**_application-v_** and _**application-x-v**_)?

Well, I just see https://github.com/ubuntu/yaru/pull/3458 file changed
And follow the java and javascript example

2022-09-28 10:53 UTC, Jupi007 commented
Well, in fact we need to use real mimetype to avoid any problem :)
The `applications-x-hwp` really exist for example: https://reposcope.com/mimetype/application/x-hwp
Same for java and javascript.

Btw sorry to not have asked this question before, but what's happening if you look at a `.v` file properties (Ctrl+I)?
Is there any mimetype associated?

2022-09-28 11:10 UTC, enghitalo commented
> Well, in fact we need to use real mimetype to avoid any problem :) The `applications-x-hwp` really exist for example: https://reposcope.com/mimetype/application/x-hwp Same for java and javascript.
> 
> Btw sorry to not have asked this question before, but what's happening if you look at a `.v` file properties (Ctrl+I)? Is there any mimetype associated?
Well, I have this.
![image](https://user-images.githubusercontent.com/63821277/192764575-607c6f29-325f-4382-9a00-8123c7069ccc.png)

2022-09-28 11:17 UTC, enghitalo commented
Sometime show as verilog type
![image](https://user-images.githubusercontent.com/63821277/192765752-8b651738-3557-49b9-b55c-513d38c093ac.png)

2022-09-28 11:18 UTC, Jupi007 commented
This one is empty (0 bytes), which mean it will have text-plain by default.
Have you got a real .v file? :)

2022-09-28 11:19 UTC, enghitalo commented
> This one is empty (0 bytes), which mean it will have text-plain by default. Have you got a real .v file? :)

Some time is read as `Verilog source code (text/x-verilog)`

2022-09-28 11:32 UTC, Jupi007 commented
Oh 😕 I think we have the same problem as here: #2398
`.v` files are grabbing the wrong mimetype...

I'm sorry but in this situation, even if we add your icon, it will be never used 🤕
The only solution is to ask the Ubuntu maintainer to add a new mimetype (I have no idea of how you can do this).

2022-09-28 14:39 UTC, enghitalo commented
> Oh 😕 I think we have the same problem as here: #2398
> `.v` files are grabbing the wrong mimetype...
> 
> I'm sorry but in this situation, even if we add your icon, it will be never used 🤕
> The only solution is to ask the Ubuntu maintainer to add a new mimetype (I have no idea of how you can do this).

Hi. By, what I have understood about this convertion -> https://discord.com/channels/592103645835821068/630144782370471978/1024675580102328421

V developers can priorize vlang instead verilog in linux config.

2022-09-28 17:24 UTC, Jupi007 commented
Okay, if you can do this we are fine :+1: 
So which mimetype is the correct one?

2022-09-28 18:37 UTC, enghitalo commented
> Okay, if you can do this we are fine +1 So which mimetype is the correct one?

text-x-v look good
text/v...

2022-09-28 18:41 UTC, Jupi007 commented
I also think `text-x-v` is the good one.
About `text/v`, all `-x` mimetypes are an extension of the standard ones, so I don't think it would be useful to include it.
Same for the `applications-*` you added.
Imo `text-x-v` is enough.

But don't worry, you will still be able to add some symlinks if really needed :)

So please fix the icon with my change request, and we will be fine for merging!

2022-09-28 20:18 UTC, enghitalo commented
Done?

2022-09-28 20:22 UTC, Jupi007 requested changes
Sorry, but you forgotten to use a folded background as I said upper (like here: https://github.com/ubuntu/yaru/blob/master/icons/src/fullcolor/default/mimetypes/text-x-c.svg).

And this is my last change request :)

2022-09-29 09:59 UTC, Jupi007 approved these changes
LGFM :+1: 

Thanks a lot for your patience @enghitalo ❤️

I don't know if we can merge this now (because of the UI freeze), but you're done :)

2022-09-29 10:31 UTC, enghitalo commented
Thank you for all support ❤️

2022-11-18 09:36 UTC, Jupi007 commented
Merging, this will be included in the next ubuntu release :)

2022-11-18 09:36 UTC, merged