Prepare cinnamon theme variants
ubuntu/yaru pull request #3842
Opened 2023-03-15 14:51 UTC by hsbasu

- set cinnamon component option to true
- add colorable assets file
- Update the meson build script to create variants
- Follow the way gnome-shell variants are created
- Not using directories cinnamon, cinnamon-dark, dark and default. Can be cleaned up later.

2023-03-15 14:57 UTC, hsbasu commented
Hi @Jupi007 The PR for cinnamon variants you requested. Please have a look.

2023-03-16 06:46 UTC, Initu-Castilhos commented
![Captura de tela de 2023-03-16 03-32-59](https://user-images.githubusercontent.com/59381215/225534902-5efada51-1f9b-4309-9e46-ab1a14ed5d08.png)
The light version has a lot of contrast between the separator and the corner bar.
![Captura de tela de 2023-03-16 03-33-27](https://user-images.githubusercontent.com/59381215/225535448-5817a7e3-491c-4204-85f4-16998b0cb671.png)
The dark version is ok.
![Captura de tela de 2023-03-16 03-41-11](https://user-images.githubusercontent.com/59381215/225535725-03f1017c-90ea-4b6f-8b3a-6a663e2c3a4e.png)
The checked and radio are 24px and the radio is light in the dark version. Take a look at this P.R. done: https://github.com/ubuntu/yaru/pull/3794

2023-03-16 09:12 UTC, Jupi007 requested changes
Hi @hsbasu and thanks a lot for this PR!
This is much appreciated ❤️

I added some requested change.

2023-03-16 09:12 UTC, Jupi007 commented on cinnamon-shell/src/sass/_tweaks.scss
> +    height: 24px;
Can you revert the control's size to 20px like before?

```suggestion
    width: 20px;
    height: 20px;
```

2023-03-16 09:12 UTC, Jupi007 commented on cinnamon-shell/src/assets/colorable-assets/checkbox/radio-unchecked.svg
@ItzSwirlz noticed that controls was white in the dark theme.

2023-03-16 09:12 UTC, Jupi007 commented on cinnamon-shell/src/assets/colorable-assets/checkbox/checkbox-checked-focused.svg
You've used our old checkmark, see #3793

2023-03-16 09:12 UTC, Jupi007 commented on cinnamon-shell/meson.build
Can you clean in this PR the unused folders, please?

2023-03-16 09:14 UTC, Jupi007 commented
>  The light version has a lot of contrast between the separator and the corner bar.

@ItzSwirlz Is this problem reproducible in `master`, or only in this PR?

2023-03-16 12:31 UTC, hsbasu commented on test-yaru
No. I was getting trouble to test the themes as it asks for sudo password every time. So I researched and created it. Kept it because others can simply run it while testing. I don't see any harm keeping it. So I kept it.

2023-03-16 12:38 UTC, Jupi007 commented on test-yaru
Okay, what you can do is create a local git ignore: https://stackoverflow.com/a/1753078
So you don't need to commit this file to our repo 🙂

2023-03-16 14:11 UTC, hsbasu commented on meson_options.txt
> +option('cinnamon-shell', type: 'boolean', value: true, description:'build cinnamon component')
Done.

2023-03-16 14:12 UTC, hsbasu commented on test-yaru
Removed it.

2023-03-16 14:33 UTC, Jupi007 commented on test-yaru
Thanks 👍

2023-03-16 14:58 UTC, hsbasu commented on cinnamon-shell/src/assets/colorable-assets/checkbox/radio-unchecked.svg
Done.

2023-03-16 14:58 UTC, hsbasu commented on cinnamon-shell/src/assets/colorable-assets/checkbox/checkbox-checked-focused.svg
Done.

2023-03-16 15:07 UTC, Jupi007 commented
@hsbasu Thanks a lot to have applied my requested changes 🙂
I don't know why, but it looks like you messed up the commits because some of my previous PRs changes pop up here 🤔

@Initu-Castilhos Can you retest this PR, please?
I need to setup a cinnamon VM, but it could be nice to have a quicker feedback, especially for the separator problem.

2023-03-16 15:27 UTC, Initu-Castilhos commented
> > A versão light tem muito contraste entre o separador e a barra de canto.
> 
> @Initu-CastilhosEste problema é reproduzível em `master`, ou apenas neste PR?

Master.

2023-03-16 15:52 UTC, Initu-Castilhos commented
![Captura de tela de 2023-03-16 12-49-17](https://user-images.githubusercontent.com/59381215/225675619-c39ec3c6-c35c-4357-a369-e11048b77072.png)
![Captura de tela de 2023-03-16 12-49-25](https://user-images.githubusercontent.com/59381215/225675675-c96563e0-1883-4965-b9a5-4fa019c9a56f.png)
It's not coloring.

2023-03-16 18:05 UTC, Initu-Castilhos commented
Maybe it's better to change the color of the panel and base it on the titlebar color like in Mint-Y.

2023-03-16 18:40 UTC, hsbasu commented
@Initu-Castilhos @Jupi007 @ItzSwirlz Corrected everything. Please have a look.

2023-03-16 19:13 UTC, Initu-Castilhos commented
![Captura de tela de 2023-03-16 16-12-50](https://user-images.githubusercontent.com/59381215/225728858-8a651f40-4543-4ed0-b2ef-e96818ccba38.png)
Nothing yet.

2023-03-16 19:19 UTC, hsbasu commented
> ![Captura de tela de 2023-03-16 16-12-50](https://user-images.githubusercontent.com/59381215/225728858-8a651f40-4543-4ed0-b2ef-e96818ccba38.png) Nothing yet.

It's strange. I rebased all the scss files from the `default` folder. I was able to generate all the variants and assets properly. Let me try again.

2023-03-16 19:45 UTC, hsbasu commented
I get it now. Those colours are coming from the sass files and are not using accent_bg_colour as their base. To modify those colours, the sass files need to be modified. I have cross checked all the colorizable assests are taking accent colour.

2023-04-02 22:48 UTC, Initu-Castilhos commented
> @Initu-Castilhos @Jupi007Agora eu entendi. Essas cores vêm dos arquivos sass e não estão usando acent_bg_colour como base. Para modificar essas cores, os arquivos sass precisam ser modificados. Eu verifiquei se todos os recursos colorizáveis ​​estão usando cores de destaque. Eu sugeriria ter um commit separado para eles.

I found this project: https://github.com/dgsasha/dg-yaru

2023-05-04 03:48 UTC, hsbasu commented
@Jupi007 A gentle reminder on the PR.

2023-05-05 09:12 UTC, Jupi007 approved these changes
Hi @hsbasu,
sorry for the late reply.

Imo, this can be merged.
But I would like to have @Muqtxdir approval before.

2023-06-16 16:34 UTC, Muqtxdir approved these changes
thanks

2023-06-16 16:48 UTC, merged

2023-06-16 16:49 UTC, Jupi007 commented
Thanks a lot for this PR @hsbasu 👍
And sorry for the delay.

2023-06-16 17:03 UTC, hsbasu commented
It's ok.

2023-06-16 17:05 UTC, Jupi007 commented
@hsbasu it is already merged 🙂

2023-06-16 17:05 UTC, Feichtmeier commented
![grafik](https://github.com/ubuntu/yaru/assets/15329494/2453f0aa-97e2-4f99-8b42-7d09b4225713)
 :D

2023-06-16 17:07 UTC, hsbasu commented
😁 didn't see that it's already merged.

2023-06-16 21:20 UTC, Initu-Castilhos commented
It does not complete the installation.

2023-06-17 09:21 UTC, Jupi007 commented
@Initu-Castilhos I did a fix PR here: #3921
Can you test it?